import os
import requests
from datetime import datetime
from groq import Groq
import pytz

# ── API Keys (loaded from environment / GitHub Secrets) ──────────────────────
GROQ_API_KEY        = os.environ["GROQ_API_KEY"]
TAVILY_API_KEY      = os.environ["TAVILY_API_KEY"]
TELEGRAM_BOT_TOKEN  = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHANNEL_ID = os.environ["TELEGRAM_CHANNEL_ID"]      # e.g. @YourChannelName or -100xxxxxxxxxx
CALLMEBOT_PHONE     = os.environ.get("CALLMEBOT_PHONE", "")  # optional: +91XXXXXXXXXX
CALLMEBOT_APIKEY    = os.environ.get("CALLMEBOT_APIKEY", "")  # optional

# ── Step 1: Search latest market news via Tavily ─────────────────────────────
def search_market_news():
    queries = [
        "India NSE Nifty 50 Sensex stock market today",
        "US S&P 500 NASDAQ Dow Jones stock market today",
        "European stocks FTSE 100 DAX CAC 40 today",
        "China Shanghai Composite Hang Seng today",
        "Japan Nikkei 225 South Korea KOSPI today",
        "crude oil Brent WTI gold silver commodities price today",
        "tech stocks AI semiconductor big tech news today",
        "Fed RBI ECB central bank economic data macro news today",
    ]
    all_results = []
    for query in queries:
        resp = requests.post(
            "https://api.tavily.com/search",
            json={
                "api_key": TAVILY_API_KEY,
                "query": query,
                "search_depth": "advanced",
                "max_results": 3,
                "include_published_date": True,
            },
            timeout=15,
        )
        if resp.status_code == 200:
            all_results.extend(resp.json().get("results", []))
    return all_results


def build_context(results):
    ctx = ""
    for r in results:
        ctx += (
            f"\nTitle: {r.get('title','')}"
            f"\nURL: {r.get('url','')}"
            f"\nDate: {r.get('published_date','N/A')}"
            f"\nContent: {r.get('content','')[:600]}"
            f"\n{'─'*60}"
        )
    return ctx


# ── Step 2: Generate brief with Groq (free) ──────────────────────────────────
def generate_brief(date_str, context):
    client = Groq(api_key=GROQ_API_KEY)

    prompt = f"""You are a professional financial analyst and market intelligence agent.
Generate a structured "Global Morning Market Brief" for {date_str}.

Use ONLY the search results below as your source. Never fabricate prices, numbers, or headlines.
If specific data is unavailable, write "Data unavailable at report time."

────────────────── LIVE SEARCH RESULTS ──────────────────
{context}
─────────────────────────────────────────────────────────

CRITICAL RULES — YOU MUST FOLLOW THESE:
1. Every single headline or claim MUST have an inline clickable link using EXACTLY this Telegram markdown format: [Headline text](URL)
   Use the URLs from the search results above. Never write a headline without its URL.
2. Every source must show: [Headline](URL) — Source Name, Date
3. NEVER write "Sources cited above" or "Source: X" as plain text — always embed the URL as a clickable link.
4. If a URL is not available for a claim, do NOT include that claim.

Produce output in this EXACT format:

🌍 *GLOBAL MORNING MARKET BRIEF — {date_str}*
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 *1. MARKET SNAPSHOTS*

For each market write:
• Headline as clickable link: [Headline text](https://actual-url-from-search-results.com) — Source, Date
• 3-sentence market summary
• Sentiment: [🟢 Bullish / 🔴 Bearish / 🟡 Neutral] — one-line reason

🇮🇳 *INDIA — NSE Nifty 50 & BSE Sensex*
[content with clickable links]

🇺🇸 *USA — S&P 500, NASDAQ, Dow Jones*
[content with clickable links]

🇪🇺 *EUROPE — FTSE 100, DAX, CAC 40*
[content with clickable links]

🇨🇳 *CHINA — Shanghai Composite & Hang Seng*
[content with clickable links]

🇯🇵 *JAPAN — Nikkei 225*
[content with clickable links]

🇰🇷 *SOUTH KOREA — KOSPI*
[content with clickable links]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛢️ *2. COMMODITIES PULSE*

For Brent Crude, WTI Crude, Gold, Silver, Natural Gas write:
• Price + % change (if available)
• [Key news headline](URL) — Source, Date
• Impact on equity markets or sectors

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💻 *3. TECH & MACRO CATALYST*

• [Tech headline](URL) — Source, Date — market impact
• [Tech headline](URL) — Source, Date — market impact
• [Central bank headline](URL) — Source, Date — market impact

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💡 *4. LEARNING OF THE DAY*

*Concept:* [Name of concept]
*Today's example:* [2–3 sentences connecting it to today's news]
*The lesson:* [1–2 actionable sentences for investors/traders]
*Read more:* [Book title or search term]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️ *5. RISK RADAR — Next 24–48 Hours*

• [Event 1](URL): brief description
• [Event 2](URL): brief description
• [Event 3](URL): brief description

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
_Generated by Market Brief AI Agent — {date_str}_"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=2500,
    )
    return response.choices[0].message.content


# ── Step 3: Deliver to Telegram ───────────────────────────────────────────────
def send_telegram(brief):
    max_len = 4096
    # Split on paragraph boundaries to keep formatting intact
    parts = []
    while len(brief) > max_len:
        split_at = brief.rfind("\n", 0, max_len)
        if split_at == -1:
            split_at = max_len
        parts.append(brief[:split_at])
        brief = brief[split_at:].lstrip()
    parts.append(brief)

    for i, part in enumerate(parts):
        resp = requests.post(
            f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
            json={
                "chat_id": TELEGRAM_CHANNEL_ID,
                "text": part,
                "parse_mode": "Markdown",
                "disable_web_page_preview": True,
            },
            timeout=15,
        )
        if resp.status_code != 200:
            print(f"Telegram error on part {i+1}: {resp.text}")
    print(f"✅ Sent {len(parts)} Telegram message(s).")


# ── Step 4: Deliver to WhatsApp via CallMeBot (free, personal) ───────────────
def send_whatsapp(brief):
    if not (CALLMEBOT_PHONE and CALLMEBOT_APIKEY):
        return
    # WhatsApp / CallMeBot has a shorter limit — send a condensed version
    summary = brief[:1500] + "\n\n📲 Full report on our Telegram channel!"
    encoded = requests.utils.quote(summary)
    url = (
        f"https://api.callmebot.com/whatsapp.php"
        f"?phone={CALLMEBOT_PHONE}&text={encoded}&apikey={CALLMEBOT_APIKEY}"
    )
    resp = requests.get(url, timeout=15)
    if resp.status_code == 200:
        print("✅ WhatsApp notification sent.")
    else:
        print(f"WhatsApp error: {resp.text}")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    ist = pytz.timezone("Asia/Kolkata")
    date_str = datetime.now(ist).strftime("%B %d, %Y")
    print(f"\n📰 Generating Market Brief for {date_str} ...\n")

    print("🔍 Searching latest market news...")
    results = search_market_news()
    context = build_context(results)
    print(f"   Found {len(results)} articles.\n")

    print("🤖 Generating AI brief with Groq (Llama 3.3 70B)...")
    brief = generate_brief(date_str, context)
    print("   Brief generated.\n")

    print("📤 Sending to Telegram...")
    send_telegram(brief)

    print("📱 Sending WhatsApp notification...")
    send_whatsapp(brief)

    print("\n🎉 All done!")


if __name__ == "__main__":
    main()
